name: Doc-Release

on:
  # When a new (empty) release is created via the GitHub UI, uploads the files to that release
  # and upload the doc to GitHub pages. Only do this when all the tests are passing. 
  release:
    types:
      - created

  # Also, on every commit to the main branch, build the HTML documentation using Sphinx to make sure it's not broken
  push:
    branches: [ master, release ]
  
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache Python deps (get location)
        id: pip-cache
        run: |
            python -m pip install -U "pip>=20.1"
            echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache Python deps
        uses: actions/cache@v2
        with:
            path: ${{ steps.pip-cache.outputs.dir }}
            key: generate-doc-pip

      - name: Python dependencies - install
        id: deps
        run: |
          # Peg these versions so we only upgrade when we want to
          pip install docutils==0.16 sphinx==3.0.1 sphinx-epytext==0.0.4 sphinx_rtd_theme==0.4.3 sphinx-autodocgen==1.2

      - name: Build
        shell: bash
        run: |
          python xpybuild.py --buildfile release-xpy.xpybuild.py
         
      - name: Upload doc as an artifact
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: _build_output/docs/html/*

      - name: Upload to gh-pages
        if: github.event_name == 'release'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: _build_output/docs/html

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        id: upload-release-asset 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          file: _build_output/*.zip
