name: Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    
  workflow_dispatch: # also allow manually invoking this

  schedule:
      - cron: '25 0 1 */2 *' # run on the default branch once every 2 months (25mins past the hour to avoid peak load)

jobs:
  test:
    strategy:
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      
      matrix:
        include:
          # oldest supported version
          - test-run-id: ubuntu-py3.10
            os: ubuntu-latest
            python-version: "3.10"
            perf-test: true

          # newest supported version
          - test-run-id: win-py3.13
            os: windows-latest
            python-version: "3.13"
            perf-test: false

    runs-on: ${{matrix.os}}
    
    steps:
      # Install the desired version of Python and PySys
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}
          # Enabled caching of dependencies
          cache: pip
          cache-dependency-path: tests/pysys-requirements.txt
      - run: pip install -r tests/pysys-requirements.txt

      - name: Test with PySys
        working-directory: tests/correctness
        shell: bash
        id: pysys
        run: |
         
          if [[ "${{ matrix.perf-test }}" = "true" ]]; then 
            cd ..
            echo Running ALL tests from `pwd`
          fi
          
          python -m pysys run --ci --outdir=${{matrix.test-run-id}} --exclude skip_ci

      - name: Upload Python code coverage 
        # codecov@v2.1.0
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
        if: steps.pysys.outputs.artifact_PythonCoverageDir
        with:
          name: ${{matrix.test-run-id}}
          #files: ${{ steps.pysys.outputs.artifact_PythonCoverageDir }}/coverage.xml
          directory: ${{ steps.pysys.outputs.artifact_PythonCoverageDir }}

      # If any tests fail, PySys will return an error code, so we need "if: always()" so the following steps will run
      
      - name: Upload performance CSV artifacts
        # upload-artifact@v2.3.1
        uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47
        # Only do this if some performance results were generated
        if: always() && steps.pysys.outputs.artifact_CSVPerformanceReport

        with:
          name: pysys_performance_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_CSVPerformanceReport }}

      - name: Upload archive artifacts for any test failures
        # upload-artifact@v2.3.1
        uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47
        if: always() && steps.pysys.outputs.artifact_TestOutputArchiveDir

        with:
          name: pysys_output_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_TestOutputArchiveDir }}
